name: Little Blue
encoding: UTF-8
pygments: true
markdown: redcarpet
redcarpet:
    extensions: 
        - smart
        - tables
        - autolink
        - superscript
        - strikethrough
        - no_intra_emphasis
