name: Twitchy
encoding: UTF-8
pygments: true
redcarpet:
    extensions: 
        - smart
        - tables
        - autolink
        - superscript
        - strikethrough
        - no_intra_emphasis
gems:
    - jekyll-pandoc-multiple-formats
markdown: pandoc
pandoc:
    skip: true
    output: './tmp'
    flags: '--smart'
    site_flags: '--toc'
    outputs:
        pdf:
        epub:
