#source "https://rubygems.org"
#gem 'foundation'

gem 'sass',     :github => 'nex3/sass',             :tag => '3.3.0.rc.2'
gem 'compass',  :github => 'chriseppstein/compass', :tag => '1.0.0.alpha.17'
gem 'susy',     :github => 'ericam/susy',           :tag => '2.0.0.beta.3'

#gem 'compass-normalize-plugin', :github => 'jzorn/compass-normalize-plugin'
#gem 'sassy-buttons',            :github => 'jhardy/Sassy-Buttons'

